### ISSUE TITLE
Parent recipe relationship should be unidirectional

### ISSUE THREAD

**Issue by vegaelle** [gordon-/atable#7]
Actually, when we add a parent recipe to another recipe, the relationship is bidirectionnal, making each recipe parent for the other one.

There should be a hierarchical relationship between recipes.

**Comment by opi** [comment]
but we need a method to list child recipes when viewing a parent recipe detailView

**Comment by vegaelle** [comment]
That’s not a problem. The fix should be a “through” model between recipes, with “child” and “parent” attributes.
